### ISSUE TITLE
result.Append does not modify the instance you call it on

### ISSUE THREAD

**Issue by jmbeach** [hylasoft-usa/h-resolution#17]
By looking at the following code from the README, I would expect that the result variable would have a new entry in it after calling the append method:

```c#
if (result.Contains(targetCode))
		result.AppendTrace("Result contains '{0}'.", targetCode);
```

However, this is not what I'm seeing in my project unless I modify the code like so:

```c#
if (result.Contains(targetCode))
		result = result.AppendTrace("Result contains '{0}'.", targetCode);
```

**Comment by jcooley-hylasoft** [comment]
The documentation is incorrect.  Results are immutable by design, so Append would never modify them directly.
